name: Run Tests and Generate Code Coverage Report

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test-and-coverage:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the Code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            # Step 3: Install Dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Run Tests and Generate Coverage
            - name: Run Tests with Coverage
              run: npm test -- --watchAll=false --coverage

            # Step 5: Upload Test Coverage Report as Artifact
            - name: Upload Coverage Report
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-report
                  path: coverage

            # Step 6: Display Coverage Summary in Logs (Optional)
            - name: Display Coverage Summary
              run: cat coverage/lcov-report/index.html
